# Generated by Django 4.1 on 2022-08-25 13:27

import api.behaviours
from django.db import migrations, models
import django.db.models.functions.datetime
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=api.behaviours.AutoCreatedField(default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='category',
            name='modified',
            field=api.behaviours.AutoLastModifiedField(default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='created',
            field=api.behaviours.AutoCreatedField(default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='customer',
            name='modified',
            field=api.behaviours.AutoLastModifiedField(default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=api.behaviours.AutoCreatedField(default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='order',
            name='modified',
            field=api.behaviours.AutoLastModifiedField(default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=api.behaviours.AutoCreatedField(default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=api.behaviours.AutoLastModifiedField(default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='created',
            field=api.behaviours.AutoCreatedField(default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='stock',
            name='modified',
            field=api.behaviours.AutoLastModifiedField(default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='stock',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
