# Generated by Django 4.1 on 2022-08-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_created_category_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
        migrations.RemoveField(
            model_name='category',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='category',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='uuid',
        ),
    ]
