# Generated by Django 4.1 on 2022-08-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_category_created_remove_category_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='is_deleted',
        ),
    ]
